from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title='IAM API',
        default_version='v1',
        description="""
        This application keeps track of the access tokens of Sociall.me
        users for various platforms (like Google, Facebook, Twitter).

        Users are identified with unique user IDs. These unique IDs are
        generated by another microservice, in which users of Sociall.me
        are managed.
        """,
        contact=openapi.Contact(email='developers@artistanbul.io'),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
